using SMS.Domain.Entities;
using SMS.Domain.Enums;
using System;
using System.Collections.Generic;
using System.Threading;
using System.Threading.Tasks;

namespace SMS.Domain.Interfaces
{
    /// <summary>
    /// Repository interface for ReportVerification entities.
    /// </summary>
    public interface IReportVerificationRepository : IRepository<ReportVerification>
    {
        /// <summary>
        /// Gets a report verification record by its verification token.
        /// </summary>
        Task<ReportVerification?> GetByTokenAsync(string token, CancellationToken cancellationToken = default);

        /// <summary>
        /// Gets a report verification record by its Report ID.
        /// </summary>
        Task<ReportVerification?> GetByReportIdAsync(string reportId, CancellationToken cancellationToken = default);

        /// <summary>
        /// Gets all verification records for a specific report type.
        /// </summary>
        Task<IEnumerable<ReportVerification>> GetByReportTypeAsync(string reportType, CancellationToken cancellationToken = default);

        /// <summary>
        /// Gets all verification records generated by a specific user.
        /// </summary>
        Task<IEnumerable<ReportVerification>> GetByGeneratedByAsync(string userId, CancellationToken cancellationToken = default);

        /// <summary>
        /// Gets verification records with filtering and pagination.
        /// </summary>
        Task<(IEnumerable<ReportVerification> records, int totalCount)> GetFilteredAsync(
            string? reportType = null,
            string? reportId = null,
            string? generatedBy = null,
            ReportVerificationStatus? status = null,
            DateTime? startDate = null,
            DateTime? endDate = null,
            int page = 1,
            int pageSize = 50,
            CancellationToken cancellationToken = default);

        /// <summary>
        /// Checks if a verification token already exists.
        /// </summary>
        Task<bool> TokenExistsAsync(string token, CancellationToken cancellationToken = default);

        /// <summary>
        /// Checks if a Report ID already exists.
        /// </summary>
        Task<bool> ReportIdExistsAsync(string reportId, CancellationToken cancellationToken = default);

        /// <summary>
        /// Gets the total count of verification records with optional filtering.
        /// </summary>
        Task<int> GetCountAsync(
            ReportVerificationStatus? status = null,
            string? reportType = null,
            DateTime? startDate = null,
            DateTime? endDate = null,
            CancellationToken cancellationToken = default);
    }
}
