-- ============================================================================
-- DEPRECATED - DO NOT USE. This file previously contained SQL Server flavoured
-- seed statements (GETUTCDATE, unquoted PascalCase identifiers) that are NOT
-- valid on the production PostgreSQL database and were NOT row-level-security
-- aware.
--
-- The authorised seed path is the EF Core migration:
--   src/SMS.Persistence/Migrations/20260908120000_SeedAssessmentGradingData.cs
-- which seeds the 13 assessment types, the default grading scale (A/B/C/F with
-- the institutional boundaries), and the default certificate eligibility rule
-- in an idempotent, tenant-aligned way.
-- ============================================================================