using SMS.Domain.Common;
using SMS.Domain.Enums;
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace SMS.Domain.Entities
{
    /// <summary>
    /// An OMS order (aggregate root). Lifecycle state is changed only through the
    /// transition methods (see <see cref="Common.OrderLifecycle"/>); the order
    /// number is generated server-side via IOrderNumberGenerator and is immutable
    /// after creation; TotalAmount is derived from items, never trusted from
    /// client input. Monetary values use decimal with half-even rounding
    /// (<see cref="Common.OmsMoney"/>). Development defaults per
    /// Documentation/OMS/OMS_OPEN_REQUIREMENTS.md.
    /// </summary>
    [Table("oms_orders")]
    public class Order : BaseEntity, ITenantAwareEntity
    {
        /// <summary>Tenant-unique, server-generated, immutable order number (ORD-yyyy-nnnnnn).</summary>
        [Required]
        [MaxLength(50)]
        public string OrderNumber { get; private set; } = string.Empty;

        [Required]
        [MaxLength(200)]
        public string Title { get; private set; } = string.Empty;

        [MaxLength(2000)]
        public string? Description { get; private set; }

        /// <summary>Lifecycle status. Change only via the transition methods.</summary>
        public OrderStatus Status { get; private set; } = OrderStatus.Draft;

        /// <summary>User id of the order creator (requested by).</summary>
        [Required]
        [MaxLength(100)]
        public string RequestedByUserId { get; private set; } = string.Empty;

        [MaxLength(100)]
        public string? ApprovedByUserId { get; private set; }

        public DateTime? ApprovedAtUtc { get; private set; }

        [MaxLength(1000)]
        public string? ApprovalRemarks { get; private set; }

        [MaxLength(100)]
        public string? RejectedByUserId { get; private set; }

        public DateTime? RejectedAtUtc { get; private set; }

        [MaxLength(1000)]
        public string? RejectionRemarks { get; private set; }

        [MaxLength(100)]
        public string? CancelledByUserId { get; private set; }

        public DateTime? CancelledAtUtc { get; private set; }

        [MaxLength(1000)]
        public string? CancellationReason { get; private set; }

        public DateTime? SubmittedAtUtc { get; private set; }

        /// <summary>Optional business-required delivery date.</summary>
        public DateTime? RequiredByDate { get; private set; }

        /// <summary>
        /// Optional road-account linkage (plain reference, no FK — open
        /// requirement #18; Road Accounting rules are not configured yet).
        /// </summary>
        public Guid? RoadAccountId { get; private set; }

        /// <summary>Order total derived from items (decimal(18,2), half-even rounding).</summary>
        [Column(TypeName = "numeric(18,2)")]
        public decimal TotalAmount { get; private set; }

        /// <summary>ISO-4217 currency code (development default KES, open requirement #16).</summary>
        [Required]
        [MaxLength(3)]
        public string Currency { get; private set; } = OmsMoney.DefaultCurrency;

        // Navigation properties
        public virtual ICollection<OrderItem> Items { get; private set; } = new List<OrderItem>();
        public virtual ICollection<OrderStatusHistory> StatusHistory { get; private set; } = new List<OrderStatusHistory>();
        public virtual ICollection<OrderAttachment> Attachments { get; private set; } = new List<OrderAttachment>();
        public virtual ICollection<OrderManifest> Manifests { get; private set; } = new List<OrderManifest>();

        /// <summary>
        /// Creates a new Draft order. <paramref name="orderNumber"/> must come from
        /// <see cref="Interfaces.IOrderNumberGenerator"/>; Status starts at Draft.
        /// </summary>
        public static Order Create(
            string orderNumber,
            string title,
            string? description,
            string requestedByUserId,
            string currency,
            DateTime? requiredByDate,
            Guid? roadAccountId = null)
        {
            if (string.IsNullOrWhiteSpace(orderNumber))
            {
                throw new ArgumentException("Order number is required and must be generated by IOrderNumberGenerator.", nameof(orderNumber));
            }

            if (!OmsOrderNumber.IsValidFormat(orderNumber))
            {
                throw new ArgumentException($"Order number '{orderNumber}' does not match the canonical format ORD-yyyy-nnnnnn.", nameof(orderNumber));
            }

            if (string.IsNullOrWhiteSpace(title))
            {
                throw new ArgumentException("Order title is required.", nameof(title));
            }

            if (title.Length > 200)
            {
                throw new ArgumentException("Order title must not exceed 200 characters.", nameof(title));
            }

            if (!string.IsNullOrEmpty(description) && description.Length > 2000)
            {
                throw new ArgumentException("Order description must not exceed 2000 characters.", nameof(description));
            }

            if (string.IsNullOrWhiteSpace(requestedByUserId))
            {
                throw new ArgumentException("Requesting user is required.", nameof(requestedByUserId));
            }

            if (string.IsNullOrWhiteSpace(currency) || currency.Length != 3)
            {
                throw new ArgumentException("Currency must be a 3-letter ISO-4217 code.", nameof(currency));
            }

            return new Order
            {
                OrderNumber = orderNumber,
                Title = title,
                Description = description,
                RequestedByUserId = requestedByUserId,
                Currency = currency.ToUpperInvariant(),
                RequiredByDate = requiredByDate,
                RoadAccountId = roadAccountId,
                Status = OrderStatus.Draft,
                TotalAmount = 0m
            };
        }

        /// <summary>Adds an item to the order (Draft only). Line total and order total are recalculated.</summary>
        public OrderItem AddItem(string? itemCode, string description, int quantity, decimal unitPrice)
        {
            EnsureEditable();
            var item = OrderItem.Create(itemCode, description, quantity, unitPrice);
            item.AssignRowNumber(Items.Count + 1);
            Items.Add(item);
            RecalculateTotal();
            return item;
        }

        /// <summary>Removes an item from the order (Draft only). Order total is recalculated.</summary>
        public void RemoveItem(Guid itemId)
        {
            EnsureEditable();
            OrderItem? item = null;
            foreach (var candidate in Items)
            {
                if (candidate.Id == itemId)
                {
                    item = candidate;
                    break;
                }
            }

            if (item == null)
            {
                throw new InvalidOperationException($"Order item {itemId} was not found on order {OrderNumber}.");
            }

            Items.Remove(item);
            RecalculateTotal();
        }

        /// <summary>Number of items currently on the order.</summary>
        public int ItemCount => Items.Count;

        /// <summary>Submits the order (Draft → Submitted). Requires at least one item.</summary>
        public void Submit(string performedByUserId, string? performedByUsername)
        {
            if (Status == OrderStatus.Draft && ItemCount == 0)
            {
                throw new InvalidOperationException("An order must contain at least one item before it can be submitted (open requirement #8).");
            }

            ApplyTransition(OrderStatus.Submitted, OrderActionType.Submitted, performedByUserId, performedByUsername, null);
            SubmittedAtUtc = DateTime.UtcNow;
        }

        /// <summary>Moves a Submitted order into review (Submitted → PendingApproval).</summary>
        public void StartReview(string performedByUserId, string? performedByUsername)
        {
            ApplyTransition(OrderStatus.PendingApproval, OrderActionType.ReviewStarted, performedByUserId, performedByUsername, null);
        }

        /// <summary>
        /// Approves the order (Submitted/PendingApproval → Approved).
        /// A creator can never approve their own order (open requirement #5).
        /// </summary>
        public void Approve(string performedByUserId, string? performedByUsername, string? remarks)
        {
            if (string.Equals(performedByUserId, RequestedByUserId, StringComparison.OrdinalIgnoreCase))
            {
                throw new InvalidOperationException("The creator of an order cannot approve it (open requirement #5).");
            }

            ApplyTransition(OrderStatus.Approved, OrderActionType.Approved, performedByUserId, performedByUsername, remarks);
            ApprovedByUserId = performedByUserId;
            ApprovedAtUtc = DateTime.UtcNow;
            ApprovalRemarks = remarks;
        }

        /// <summary>Rejects the order (Submitted/PendingApproval → Rejected). Remarks are required.</summary>
        public void Reject(string performedByUserId, string? performedByUsername, string remarks)
        {
            if (string.IsNullOrWhiteSpace(remarks))
            {
                throw new ArgumentException("A rejection remark is required.", nameof(remarks));
            }

            ApplyTransition(OrderStatus.Rejected, OrderActionType.Rejected, performedByUserId, performedByUsername, remarks);
            RejectedByUserId = performedByUserId;
            RejectedAtUtc = DateTime.UtcNow;
            RejectionRemarks = remarks;
        }

        /// <summary>Cancels the order from Draft/Submitted/PendingApproval. A reason is required.</summary>
        public void Cancel(string performedByUserId, string? performedByUsername, string reason)
        {
            if (string.IsNullOrWhiteSpace(reason))
            {
                throw new ArgumentException("A cancellation reason is required.", nameof(reason));
            }

            ApplyTransition(OrderStatus.Cancelled, OrderActionType.Cancelled, performedByUserId, performedByUsername, reason);
            CancelledByUserId = performedByUserId;
            CancelledAtUtc = DateTime.UtcNow;
            CancellationReason = reason;
        }

        /// <summary>
        /// Core transition: validates against the state machine, sets the status
        /// and appends an append-only history entry (who/when/remarks).
        /// </summary>
        private void ApplyTransition(
            OrderStatus toStatus,
            OrderActionType action,
            string performedByUserId,
            string? performedByUsername,
            string? remarks)
        {
            if (string.IsNullOrWhiteSpace(performedByUserId))
            {
                throw new ArgumentException("Performing user is required.", nameof(performedByUserId));
            }

            var fromStatus = Status;
            OrderLifecycle.EnsureCanTransition(fromStatus, toStatus);
            Status = toStatus;
            StatusHistory.Add(OrderStatusHistory.Create(fromStatus, toStatus, action, performedByUserId, performedByUsername, remarks));
            UpdatedAt = DateTime.UtcNow;
        }

        /// <summary>Recomputes the order total from item line totals (never from client input).</summary>
        private void RecalculateTotal()
        {
            decimal sum = 0m;
            foreach (var item in Items)
            {
                sum += item.LineTotal;
            }

            TotalAmount = OmsMoney.Round(sum);
        }

        private void EnsureEditable()
        {
            if (!OrderLifecycle.CanEdit(Status))
            {
                throw new InvalidOperationException($"Order contents can only be edited while in Draft status (current: {Status}).");
            }
        }
    }
}
