using SMS.Domain.Common;
using SMS.Domain.Enums;

namespace SMS.Domain.Entities
{
    /// <summary>
    /// Represents the verification record for a generated report.
    /// Every report generated by the system gets a unique ReportVerification record
    /// that is used to authenticate and verify the report's integrity.
    /// </summary>
    public class ReportVerification : BaseEntity, ITenantAwareEntity
    {
        /// <summary>
        /// Globally unique Report ID in format MTS-YYYYMMDD-XXXXXXXX
        /// </summary>
        public string ReportId { get; set; } = string.Empty;

        /// <summary>
        /// Cryptographically secure verification token
        /// </summary>
        public string VerificationToken { get; set; } = string.Empty;

        /// <summary>
        /// Type of report (e.g., StudentReport, AttendanceReport, GradeReport, Transcript, etc.)
        /// </summary>
        public string ReportType { get; set; } = string.Empty;

        /// <summary>
        /// Human-readable name/title of the report
        /// </summary>
        public string ReportName { get; set; } = string.Empty;

        /// <summary>
        /// ID of the user who generated the report
        /// </summary>
        public string GeneratedByUserId { get; set; } = string.Empty;

        /// <summary>
        /// Name of the user who generated the report
        /// </summary>
        public string GeneratedByUserName { get; set; } = string.Empty;

        /// <summary>
        /// Timestamp when the report was generated (UTC)
        /// </summary>
        public DateTime GeneratedDate { get; set; } = DateTime.UtcNow;

        /// <summary>
        /// SHA-256 hash of the report content
        /// </summary>
        public string SHA256Hash { get; set; } = string.Empty;

        /// <summary>
        /// The hash algorithm used (e.g., SHA-256)
        /// </summary>
        public string HashAlgorithm { get; set; } = "SHA-256";

        /// <summary>
        /// Current verification status of the report
        /// </summary>
        public ReportVerificationStatus Status { get; set; } = ReportVerificationStatus.Valid;

        /// <summary>
        /// Number of times this report has been verified
        /// </summary>
        public int VerificationCount { get; set; }

        /// <summary>
        /// Timestamp of the last verification (UTC)
        /// </summary>
        public DateTime? LastVerified { get; set; }

        /// <summary>
        /// Timestamp when the report was revoked (UTC)
        /// </summary>
        public DateTime? RevokedDate { get; set; }

        /// <summary>
        /// ID of the administrator who revoked the report
        /// </summary>
        public string? RevokedBy { get; set; }

        /// <summary>
        /// Reason for revocation (e.g., Incorrect, Fraud, Reissued, Duplicate, Withdrawn)
        /// </summary>
        public string? RevocationReason { get; set; }

        /// <summary>
        /// Version number of the report
        /// </summary>
        public int Version { get; set; } = 1;

        /// <summary>
        /// Remarks or additional notes about the report
        /// </summary>
        public string? Remarks { get; set; }

        /// <summary>
        /// Whether the watermark is enabled for this report type
        /// </summary>
        public bool WatermarkEnabled { get; set; } = true;

        /// <summary>
        /// The watermark text to display
        /// </summary>
        public string WatermarkText { get; set; } = "Official System Generated Report";

        /// <summary>
        /// Expiration date for the report (null if no expiration)
        /// </summary>
        public DateTime? ExpirationDate { get; set; }

        // Navigation property
        public virtual User? GeneratedByUser { get; set; }
    }
}
